#!/bin/bash

#######################################################################
## libthreadar - is a library providing several C++ classes to work with threads
## Copyright (C) 2014-2024 Denis Corbin
##
## This file is part of libthreadar
##
##  libthreadar is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  libhtreadar is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with libthreadar.  If not, see <http:##www.gnu.org/licenses/>
##
######
##  to contact the author: dar.linux@free.fr
#######################################################################


if [ -z "$1" -o -z "$2" -o -z "$3" -o -z "$4" ] ; then
    echo "usage: $0 <path to dar_static> <dar archive> <temporary directory> <name of the uninstall script to build> [<target install dir>]"
    exit 1
fi

dar_static=`realpath "$1"`
source=`realpath "$2"`
tmpdir=`realpath "$3"`
uninst=`realpath "$4"`
destin="$5"

if [ -z "$destin" ] ; then
    destin="/"
    destprefix=""
else
    destin=`realpath "$destin"`
    destprefix="$destin"
fi

inst="$uninst.tmp"

if [ -e "$tmpdir" ] ; then
    echo "$tmpdir already exists, aborting"
    exit 2
else
    mkdir -p "$tmpdir"
fi

if ! $dar_static -x "$source" -R "$tmpdir" -O -w -q -Q -u "system.nfs4_acl" -N ; then
    echo "failed restoring $source to $tmpdir, $dar_static returned $?"
    exit 2
fi

cat < /dev/null > "$uninst"
cat < /dev/null > "$inst"

cd "$tmpdir"
for f in `find . -depth | sed -r 's#^./##'` ; do
    if [ ! -e "$desprefix/$f" ] ; then
	if [ -d "./$f" ] ; then
	    echo "rmdir --ignore-fail-on-non-empty \"$destprefix/$f\"" >> "$uninst"
	else
	    echo "rm -f \"$destprefix/$f\"" >> "$uninst"
	    echo "$destprefix/$f" >> "$inst"
	fi
    else
	if [ ! -d "$destprefix/$f" ] ; then
	    echo "File to install $destprefix/$f already exists, aborting"
	    exit 2
	fi
    fi
done

if ! $dar_static -x "$source" "-[" "$inst" -R "$destin" -O -n -q -Q -u "system.nfs4_acl" -N ; then
    echo "failed restoring $source with filter to $destin, $dar_static returned $?"
    rm -f "$inst" "$uninst"
    rm -rf "$tmpdir"
else
    rm -f "$inst"
    rm -rf "$tmpdir"
fi

ldconfig
