#!/bin/sh

#######################################################################
## libthreadar - is a library providing several C++ classes to work with threads
## Copyright (C) 2014-2025 Denis Corbin
##
## This file is part of libthreadar
##
##  libthreadar is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  libhtreadar is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with libthreadar.  If not, see <http:##www.gnu.org/licenses/>
##
######
##  to contact the author: dar.linux@free.fr
#######################################################################

if [ ! -f AUTHORS ] ; then
  echo "Script must be ran from the package root directory"
  exit 1
fi

# if 'make' fails because of a lack of 'Makefile' in the po subdirectory
# you probably have to tune the following environment variable according
# to your system.
NLSPATH='/usr/share/locale/%L/LC_MESSAGES/%N.cat'
export NLSPATH
# if you can't figure out the problem and can avoid having
# translated messages do the following
#
#    cp po/Makefile.sos po/Makefile
#
#

cp build/configure.ac .
cp build/Makefile.am .

libtoolize --automake
# gettextize --force
# po/generate_POTFILES.in

# aclocal -I m4
aclocal

autoconf
autoheader
cp build/ChangeLog .
automake --add-missing --gnu

chmod a-w configure.ac Makefile.am ChangeLog
if [ ! -e mkinstalldirs ]; then
cp build/mkinstalldirs .
fi



