#!/bin/bash

#######################################################################
## libthreadar - is a library providing several C++ classes to work with threads
## Copyright (C) 2014-2025 Denis Corbin
##
## This file is part of libthreadar
##
##  libthreadar is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Lesser General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  libhtreadar is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Lesser General Public License for more details.
##
##  You should have received a copy of the GNU Lesser General Public License
##  along with libthreadar.  If not, see <http:##www.gnu.org/licenses/>
##
######
##  to contact the author: dar.linux@free.fr
#######################################################################

if [ -z "$1" ] ; then
    echo "usage: <tmpdir>"
    exit 1
fi

tmpdir=`realpath "$1"`
curdir=`pwd`
parentdirname=`basename "$curdir"`
suffix=`uname -m`

if [ `dirname "$0"` != "misc" ] ; then
    echo "$0 should be run from the root directory of the dar/libdar source extracted package"
    echo "example: misc/`basename $0`"
    exit 2
fi

if [ ! -e src/libthreadar.pc ] ; then
    echo "libthreadar within this package must first be built with ./configure and make"
    exit 2
fi

if [ -e "$tmpdir" ] ; then
    echo "temporary build dir $tmpdir already exists, aborting"
    exit 2
else
    mkdir "$tmpdir"
fi

umask 022
if ! make DESTDIR="$tmpdir" install ; then
    echo "failed installing libthreadar in $tmpdir"
    exit 2
fi

target="$parentdirname-binary-$suffix"

if dar -c "$curdir/$target" -N -R "$tmpdir" -q -Q ; then
    echo ""
    echo ""
    echo "you can now copy:"
    echo "  - $target.1.dar file"
    echo "  - dar_static binary"
    echo "  - and the misc/finish_install script"
    echo "to a host that has no dev tools and no specific package management tool."
    echo ""
    echo "there you can run:"
    echo ""
    echo "   ./finish_install ./dar_static ./$target /tmp uninstall-$target"
    echo ""
    echo "keep the uninstall-$target file that will then be generated for you can"
    echo "later remove what has been installed (software upgrade), running the"
    echo "following command:"
    echo ""
    echo "   source ./uninstall-$target"
    echo ""
fi

rm -rf "$tmpdir"
